### ISSUE TITLE
Demo app clone command is not working

### ISSUE THREAD

**Issue by Wiz-Amit** [pezzolabs/docs#2]
Probably the repository `main` is not public.

This is what I got after running `npx degit https://github.com/pezzolabs/main/task-generator-app task-generator-app`
```
! could not fetch remote https://github.com/pezzolabs/main
! could not find commit hash for HEAD
```

**Comment by arielweinberger** [comment]
Hi @Wiz-Amit - apologies, that's the wrong repo name! Will fix the docs.

The correct command would be:
```
npx degit https://github.com/pezzolabs/examples/task-generator-app task-generator-app
```

**Comment by arielweinberger** [comment]
Thanks again for reporting @Wiz-Amit. I've pushed a fix to our docs repo and the updated docs should be live.

Let us know if we can help with anything else, either here or via [Discord](https://discord.gg/h5nBW5ySqQ).
